/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardNewRouteImport } from './routes/board.new'
import { Route as BoardPostIdRouteImport } from './routes/board.$postId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as BoardPostIdEditRouteImport } from './routes/board.$postId.edit'

const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardNewRoute = BoardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BoardRoute,
} as any)
const BoardPostIdRoute = BoardPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => BoardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardPostIdEditRoute = BoardPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BoardPostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$postId': typeof BoardPostIdRouteWithChildren
  '/board/new': typeof BoardNewRoute
  '/board/$postId/edit': typeof BoardPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$postId': typeof BoardPostIdRouteWithChildren
  '/board/new': typeof BoardNewRoute
  '/board/$postId/edit': typeof BoardPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$postId': typeof BoardPostIdRouteWithChildren
  '/board/new': typeof BoardNewRoute
  '/board/$postId/edit': typeof BoardPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$postId'
    | '/board/new'
    | '/board/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$postId'
    | '/board/new'
    | '/board/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$postId'
    | '/board/new'
    | '/board/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/new': {
      id: '/board/new'
      path: '/new'
      fullPath: '/board/new'
      preLoaderRoute: typeof BoardNewRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/$postId': {
      id: '/board/$postId'
      path: '/$postId'
      fullPath: '/board/$postId'
      preLoaderRoute: typeof BoardPostIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$postId/edit': {
      id: '/board/$postId/edit'
      path: '/edit'
      fullPath: '/board/$postId/edit'
      preLoaderRoute: typeof BoardPostIdEditRouteImport
      parentRoute: typeof BoardPostIdRoute
    }
  }
}

interface BoardPostIdRouteChildren {
  BoardPostIdEditRoute: typeof BoardPostIdEditRoute
}

const BoardPostIdRouteChildren: BoardPostIdRouteChildren = {
  BoardPostIdEditRoute: BoardPostIdEditRoute,
}

const BoardPostIdRouteWithChildren = BoardPostIdRoute._addFileChildren(
  BoardPostIdRouteChildren,
)

interface BoardRouteChildren {
  BoardPostIdRoute: typeof BoardPostIdRouteWithChildren
  BoardNewRoute: typeof BoardNewRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardPostIdRoute: BoardPostIdRouteWithChildren,
  BoardNewRoute: BoardNewRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
